#!/bin/dash

# Make sure there has been a previous init
if [ ! -d .girt ]; then
    echo ""$0": error: girt repository directory .girt not found"
    exit 1
fi

# Make sure that girt-add is given at least 1 command line argument and that no 
# command line argument starts with -[a-zA-Z._] or --.
if [ "$#" -eq 0 ]; then
    echo "usage: "$0" <filenames>"
    exit 1
fi
for arg in "$@"; do
    if echo "$arg" | grep -E -q '^-[a-zA-Z._]' || echo "$arg" | grep -E -q '^--.'; then
        echo "usage: "$0" <filenames>"
        exit 1
    fi
done


for filename in $@; do
    # Test that filename is valid
    if echo "$filename" | grep -E -q '^[._-]'; then
        echo ""$0": error: invalid filename '"$filename"'"
        exit 1
    fi
    
    # Test that filename refers to a file that exists, and if it does exist
    # then copy it to the index if it exists in the current directory, or if
    # it only exists in the index then delete it from the index
    # If it is in the current directory then test that it is an ordinary file
    if [ -e "$filename" ]; then
        if [ ! -f "$filename" ]; then
            echo ""$0": error: invalid filename '"$filename"'"
            exit 1
        else
            cp "$filename" .girt/index
        fi
    elif [ -e .girt/index/"$filename" ]; then
        rm .girt/index/"$filename"
    else
        echo ""$0": error: can not open '"$filename"'"
        exit 1
    fi
done
