#!/bin/dash

# Make sure there has been a previous init
if [ ! -d .girt ]; then
    echo ""$0": error: girt repository directory .girt not found"
    exit 1
fi

# Check that there are no command line arguments given
if [ "$#" -gt 0 ]; then
    echo "usage: "$0""
    exit 1
fi


if [ -f .girt/commit_messages.txt ]; then
    while read -r line; do
        echo "$line"
    done < .girt/commit_messages.txt
fi
