#!/bin/dash

# Make sure there has been a previous init
if [ ! -d .girt ]; then
    echo ""$0": error: girt repository directory .girt not found"
    exit 1
fi

# Make sure that girt-add is given at least 1 command line argument
if [ "$#" -eq 0 ]; then
    echo "usage: "$0" <filenames>"
fi


for filename in $@; do
    # Test that filename refers to a file that exists
    if [ ! -e "$filename" ]; then
        echo ""$0": error: can not open '"$filename"'"
        exit 1
    fi
    
    # Test that filename refers to a file that is an ordinary file
    if [ ! -f "$filename" ]; then
        echo ""$0": error: invalid filename '"$filename"'"
        exit 1
    fi
    
    cp "$filename" .girt/index
done
